// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"douyin/cmd/api/biz/router/api"
	"douyin/cmd/api/biz/router/follows"
	"douyin/cmd/api/biz/router/video"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	Api.Register(r)
	video.Register(r)
	follows.Register(r)
}
