// Code generated by hertz generator.

package handler

import (
	"context"
	"douyin/cmd/api/biz/model/api"
	"douyin/pkg/consts"
	"fmt"
	"net/http"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	rawUserInfo, exist := c.Get(consts.IdentityKey)
	if !exist {
		fmt.Println("not exist....")
	}
	// 正确写法
	userInfo := rawUserInfo.(*api.UserResp)
	// 错误写法
	// userInfo := rawUserInfo.(api.UserResp)

	c.JSON(http.StatusOK, utils.H{
		"message": "pong",
		"UserID":  userInfo.UserID,
	})
}
