// Code generated by hertz generator.

package main

import (
	handler "douyin/cmd/api/biz/handler"
	"douyin/cmd/api/biz/mw"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	auth := r.Group("/auth", mw.JwtMiddleware.MiddlewareFunc())
	auth.GET("/ping", handler.Ping)

	// your code ...
}
