// Code generated by hertz generator.

package api

import (
	"context"

	api "douyin/cmd/api/biz/model/api"
	"douyin/cmd/api/biz/mw"
	"douyin/cmd/api/biz/rpc"
	"douyin/kitex_gen/user"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Login .
// @router /douyin/user/login [GET]
func Login(ctx context.Context, c *app.RequestContext) {
	mw.JwtMiddleware.LoginHandler(ctx, c)
}

// Register .
// @router /douyin/user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// userClient.CreateUser()
	_, err = rpc.CreateUser(ctx, &user.CreateUserRequest{
		Username: req.Name,
		Password: req.Pwd,
	})

	// program error, not business error
	if err != nil {
		c.JSON(consts.StatusInternalServerError, nil)
	}

	mw.JwtMiddleware.LoginHandler(ctx, c)
}
